name: Generate perfcompare commands
description: Generate server and client commands for QUIC performance comparison

inputs:
  client:
    description: Client implementation (neqo, msquic, google, quiche, s2n)
    required: true
  server:
    description: Server implementation (neqo, msquic, google, quiche, s2n)
    required: true
  size:
    description: Transfer size in bytes
    required: true
  cubic:
    description: Use cubic congestion control (neqo only)
    default: 'true'
  pacing:
    description: Enable pacing (neqo only)
    default: 'true'
  neqo-path:
    description: Path to neqo binaries
    default: 'binaries'
  msquic-path:
    description: Path to msquic binaries
    default: 'binaries'
  google-path:
    description: Path to google/quiche binaries
    default: 'binaries'
  quiche-path:
    description: Path to cloudflare/quiche binaries
    default: 'binaries'
  s2n-path:
    description: Path to s2n-quic binaries
    default: 'binaries'
  testdata-path:
    description: Path to test data (certs, files)
    default: 'testdata'

outputs:
  bench-name:
    description: Benchmark name
    value: ${{ steps.generate.outputs.bench_name }}
  server-cmd:
    description: Server command
    value: ${{ steps.generate.outputs.server_cmd }}
  client-cmd:
    description: Client command (no disk writes, for benchmarking)
    value: ${{ steps.generate.outputs.client_cmd }}
  client-cmd-save:
    description: Client command (with disk writes, for transfer verification)
    value: ${{ steps.generate.outputs.client_cmd_save }}

runs:
  using: composite
  steps:
    - id: generate
      shell: bash
      env:
        CLIENT: ${{ inputs.client }}
        SERVER: ${{ inputs.server }}
        HOST: 127.0.0.1
        PORT: 4433
        SIZE: ${{ inputs.size }}
        CUBIC: ${{ inputs.cubic }}
        PACING: ${{ inputs.pacing }}
        NEQO: ${{ inputs.neqo-path }}
        MSQUIC: ${{ inputs.msquic-path }}
        GOOGLE: ${{ inputs.google-path }}
        QUICHE: ${{ inputs.quiche-path }}
        S2N: ${{ inputs.s2n-path }}
        TESTDATA: ${{ inputs.testdata-path }}
      run: |
        NAME="$CLIENT-$SERVER"

        # Neqo-specific arguments
        CC=$([[ "$CUBIC" == "true" ]] && echo "cubic" || echo "newreno")
        NEQO_ARGS="--cc $CC -Q 1"
        if [[ "$PACING" != "true" ]]; then
          NEQO_ARGS="$NEQO_ARGS --no-pacing"
        fi

        # Add interop flag when communicating with s2n or msquic
        INTEROP=""
        if [[ "$CLIENT" == "s2n" || "$SERVER" == "s2n" || "$CLIENT" == "msquic" || "$SERVER" == "msquic" ]]; then
          INTEROP="-a hq-interop"
        fi

        # Add cc/pacing to name for neqo-neqo benchmarks
        if [[ "$CLIENT" == "neqo" && "$SERVER" == "neqo" ]]; then
          NAME="$NAME-$CC"
          [[ "$PACING" != "true" ]] && NAME="$NAME-nopacing"
        fi

        # Server command
        case "$SERVER" in
          neqo)   SERVER_CMD="$NEQO/neqo-server $NEQO_ARGS $INTEROP $HOST:$PORT" ;;
          msquic) SERVER_CMD="$MSQUIC/quicinteropserver -root:$TESTDATA -listen:$HOST -port:$PORT -file:$TESTDATA/cert -key:$TESTDATA/key -noexit" ;;
          google) SERVER_CMD="$GOOGLE/quic_server --generate_dynamic_responses --port $PORT --certificate_file $TESTDATA/cert --key_file $TESTDATA/key" ;;
          quiche) SERVER_CMD="$QUICHE/quiche-server --root $TESTDATA --listen $HOST:$PORT --cert $TESTDATA/cert --key $TESTDATA/key" ;;
          s2n)    SERVER_CMD="$S2N/s2n-quic-qns interop server --www-dir $TESTDATA --certificate $TESTDATA/cert --private-key $TESTDATA/key --ip $HOST --port $PORT" ;;
        esac

        # Client commands: CLIENT_CMD has no disk writes (for benchmarking),
        # CLIENT_CMD_SAVE saves response data to disk (for transfer verification).
        case "$CLIENT" in
          neqo)
            BASE="$NEQO/neqo-client $NEQO_ARGS $INTEROP"; URL="https://$HOST:$PORT/$SIZE"
            CLIENT_CMD="$BASE $URL"
            CLIENT_CMD_SAVE="$BASE --output-dir . $URL"
            ;;
          msquic)
            CLIENT_CMD="$MSQUIC/quicinterop -test:D -custom:$HOST -port:$PORT -urls:https://$HOST:$PORT/$SIZE"
            CLIENT_CMD_SAVE="$CLIENT_CMD"
            ;;
          google)
            BASE="$GOOGLE/quic_client --disable_certificate_verification https://$HOST:$PORT/$SIZE"
            CLIENT_CMD="bash -c \"$BASE > /dev/null\""
            CLIENT_CMD_SAVE="bash -c \"$BASE > $SIZE\""
            ;;
          quiche)
            BASE="$QUICHE/quiche-client --no-verify"; URL="https://$HOST:$PORT/$SIZE"
            # Without --dump-responses the response body goes to stdout; redirect to /dev/null.
            CLIENT_CMD="bash -c \"$BASE $URL >/dev/null 2>&1\""
            CLIENT_CMD_SAVE="$BASE --dump-responses . $URL"
            ;;
          s2n)
            BASE="$S2N/s2n-quic-qns interop client --tls rustls --disable-cert-verification"
            TAIL="--local-ip $HOST https://$HOST:$PORT/$SIZE"
            # Without --download-dir the response body goes to stdout; redirect to /dev/null.
            CLIENT_CMD="bash -c \"$BASE $TAIL >/dev/null 2>&1\""
            CLIENT_CMD_SAVE="$BASE --download-dir . $TAIL"
            ;;
        esac

        {
          echo "bench_name=$NAME"
          echo "server_cmd=$SERVER_CMD"
          echo "client_cmd=$CLIENT_CMD"
          echo "client_cmd_save=$CLIENT_CMD_SAVE"
        } >> "$GITHUB_OUTPUT"
